#!/bin/bash
password=`cat openmrs-standalone-runtime.properties | grep connection.password | awk -F= '{print $2}'`
database/bin/mysql -u openmrs --password="$password" --socket=/tmp/openmrs.sock --max_allowed_packet=96M